// <auto-generated />
using BlazorWebAssembly_XestorTarefas.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorWebAssembly_XestorTarefas.Server.Migrations
{
    [DbContext(typeof(BlazorWebAssembly_XestorTarefasServerContext))]
    [Migration("20220412111246_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorWebAssembly_XestorTarefas.Shared.TarefaItem", b =>
                {
                    b.Property<int>("TarefaItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCompleta")
                        .HasColumnType("bit");

                    b.Property<string>("TarefaNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TarefaItemId");

                    b.ToTable("TarefaItem");
                });
#pragma warning restore 612, 618
        }
    }
}
